// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-delete-customers/strategies (interfaces: IAccountStrategyManager)

// Package mocks is a generated GoMock package.
package mocks

import (
	strategies "escort-book-delete-customers/strategies"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAccountStrategyManager is a mock of IAccountStrategyManager interface.
type MockIAccountStrategyManager struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountStrategyManagerMockRecorder
}

// MockIAccountStrategyManagerMockRecorder is the mock recorder for MockIAccountStrategyManager.
type MockIAccountStrategyManagerMockRecorder struct {
	mock *MockIAccountStrategyManager
}

// NewMockIAccountStrategyManager creates a new mock instance.
func NewMockIAccountStrategyManager(ctrl *gomock.Controller) *MockIAccountStrategyManager {
	mock := &MockIAccountStrategyManager{ctrl: ctrl}
	mock.recorder = &MockIAccountStrategyManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccountStrategyManager) EXPECT() *MockIAccountStrategyManagerMockRecorder {
	return m.recorder
}

// GetStrategy mocks base method.
func (m *MockIAccountStrategyManager) GetStrategy(arg0 string) strategies.IAccountStrategy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrategy", arg0)
	ret0, _ := ret[0].(strategies.IAccountStrategy)
	return ret0
}

// GetStrategy indicates an expected call of GetStrategy.
func (mr *MockIAccountStrategyManagerMockRecorder) GetStrategy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrategy", reflect.TypeOf((*MockIAccountStrategyManager)(nil).GetStrategy), arg0)
}
