// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-delete-customers/repositories (interfaces: IAccessTokenRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockIAccessTokenRepository is a mock of IAccessTokenRepository interface.
type MockIAccessTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAccessTokenRepositoryMockRecorder
}

// MockIAccessTokenRepositoryMockRecorder is the mock recorder for MockIAccessTokenRepository.
type MockIAccessTokenRepositoryMockRecorder struct {
	mock *MockIAccessTokenRepository
}

// NewMockIAccessTokenRepository creates a new mock instance.
func NewMockIAccessTokenRepository(ctrl *gomock.Controller) *MockIAccessTokenRepository {
	mock := &MockIAccessTokenRepository{ctrl: ctrl}
	mock.recorder = &MockIAccessTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccessTokenRepository) EXPECT() *MockIAccessTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteMany mocks base method.
func (m *MockIAccessTokenRepository) DeleteMany(arg0 context.Context, arg1 primitive.M) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockIAccessTokenRepositoryMockRecorder) DeleteMany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockIAccessTokenRepository)(nil).DeleteMany), arg0, arg1)
}
