// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-delete-customers/repositories (interfaces: IEscortProfileRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-delete-customers/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIEscortProfileRepository is a mock of IEscortProfileRepository interface.
type MockIEscortProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIEscortProfileRepositoryMockRecorder
}

// MockIEscortProfileRepositoryMockRecorder is the mock recorder for MockIEscortProfileRepository.
type MockIEscortProfileRepositoryMockRecorder struct {
	mock *MockIEscortProfileRepository
}

// NewMockIEscortProfileRepository creates a new mock instance.
func NewMockIEscortProfileRepository(ctrl *gomock.Controller) *MockIEscortProfileRepository {
	mock := &MockIEscortProfileRepository{ctrl: ctrl}
	mock.recorder = &MockIEscortProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEscortProfileRepository) EXPECT() *MockIEscortProfileRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIEscortProfileRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIEscortProfileRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIEscortProfileRepository)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockIEscortProfileRepository) Get(arg0 context.Context, arg1 string) (models.EscortProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(models.EscortProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIEscortProfileRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIEscortProfileRepository)(nil).Get), arg0, arg1)
}
